<?php

namespace ContainerYOeIsr4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFirebaseServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\FirebaseService' shared autowired service.
     *
     * @return \App\Service\FirebaseService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\FirebaseService'] = new \App\Service\FirebaseService((\dirname(__DIR__, 4).'/config/firebase/symfony07-firebase-adminsdk-fbsvc-7148aaa659.json'), 'https://symfony07-default-rtdb.firebaseio.com');
    }
}
