<?php

namespace ContainerYOeIsr4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParttiesRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ParttiesRepository' shared autowired service.
     *
     * @return \App\Repository\ParttiesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ParttiesRepository'] = new \App\Repository\ParttiesRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
