<?php

namespace ContainerYOeIsr4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTableFirebaseControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\TableFirebaseController' shared autowired service.
     *
     * @return \App\Controller\TableFirebaseController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\TableFirebaseController'] = $instance = new \App\Controller\TableFirebaseController(($container->privates['App\\Service\\FirebaseService'] ??= new \App\Service\FirebaseService((\dirname(__DIR__, 4).'/config/firebase/symfony07-firebase-adminsdk-fbsvc-7148aaa659.json'), 'https://symfony07-default-rtdb.firebaseio.com')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\TableFirebaseController', $container));

        return $instance;
    }
}
