<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYOeIsr4\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYOeIsr4/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerYOeIsr4.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerYOeIsr4\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerYOeIsr4\App_KernelProdContainer([
    'container.build_hash' => 'YOeIsr4',
    'container.build_id' => 'f435fc1d',
    'container.build_time' => 1752234262,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYOeIsr4');
