# config/services.yaml
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # ✅ Tu peux complètement retirer ceci :
    # Kreait\Firebase\Contract\Database:
    #     factory: ['@Kreait\Firebase\Factory', 'createDatabase']

    # ✅ Supprimer les arguments pour FirebaseService (autowiring automatique)
    App\Service\FirebaseService: ~

    # ✅ Supprimer ce service qui ne sert plus non plus
    # Kreait\Firebase\Factory:
    #     factory: ['Kreait\Firebase\Factory', 'withServiceAccount']
    #     arguments:
    #         - '%kernel.project_dir%/path/to/firebase_credentials.json'

    # Tu peux garder Cloudinary s’il est utilisé :
    App\Service\CloudinaryUploader:
        arguments:
            $cloudName: '%env(CLOUDINARY_NAME)%'
            $apiKey: '%env(CLOUDINARY_API_KEY)%'
            $apiSecret: '%env(CLOUDINARY_API_SECRET)%'
