<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Partties extends \App\Entity\Partties implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'debut' => [parent::class, 'debut', null, 16],
        "\0".parent::class."\0".'final' => [parent::class, 'final', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null, 16],
        "\0".parent::class."\0".'ligne1' => [parent::class, 'ligne1', null, 16],
        "\0".parent::class."\0".'ligne2' => [parent::class, 'ligne2', null, 16],
        "\0".parent::class."\0".'ligne3' => [parent::class, 'ligne3', null, 16],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null, 16],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null, 16],
        'debut' => [parent::class, 'debut', null, 16],
        'final' => [parent::class, 'final', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image' => [parent::class, 'image', null, 16],
        'ligne1' => [parent::class, 'ligne1', null, 16],
        'ligne2' => [parent::class, 'ligne2', null, 16],
        'ligne3' => [parent::class, 'ligne3', null, 16],
        'price' => [parent::class, 'price', null, 16],
        'titre' => [parent::class, 'titre', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
